# Generated by Django 2.2 on 2024-03-03 18:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('fullname', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='0', max_length=50)),
                ('avaliablebalance', models.CharField(default='0', max_length=50)),
                ('curentbalance', models.CharField(default='0', max_length=50)),
                ('checkingbalance', models.CharField(default='10', max_length=50)),
                ('accnumber', models.CharField(blank=True, max_length=100)),
                ('acctype', models.CharField(blank=True, max_length=10)),
                ('pair', models.CharField(blank=True, default='USD', max_length=10)),
                ('image', models.FileField(blank=True, default='pro_ny6h2o.png', upload_to='')),
                ('withdraw', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pay_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('wallet', models.CharField(default='0', max_length=500)),
                ('image', models.FileField(upload_to='')),
                ('visible', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='0', max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Veri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=50)),
                ('ssn', models.CharField(default='', max_length=50)),
                ('image1', models.FileField(blank=True, upload_to='')),
                ('image2', models.FileField(blank=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='0', max_length=50)),
                ('state', models.CharField(default='0', max_length=50)),
                ('description', models.TextField()),
                ('accountname', models.CharField(default='0', max_length=50)),
                ('accountnumber', models.CharField(default='0', max_length=50)),
                ('bankname', models.CharField(default='0', max_length=50)),
                ('ibancode', models.CharField(blank=True, default='0', max_length=50)),
                ('swiftcode', models.CharField(blank=True, default='0', max_length=50)),
                ('bankaddress', models.CharField(blank=True, default='0', max_length=50)),
                ('amount', models.CharField(default='0', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('In Progress', 'In Progress'), ('Failed', 'Failed')], default='In Progress', max_length=20)),
                ('status2', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Failed', 'Failed')], default='Debit', max_length=20)),
                ('credit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_withdraw', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=30, unique=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Local_trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=100)),
                ('amount', models.CharField(default='0', max_length=100)),
                ('ibancode', models.CharField(blank=True, default='0', max_length=50)),
                ('swiftcode', models.CharField(blank=True, default='0', max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(default='0', max_length=50)),
                ('ten', models.CharField(default='0', max_length=50)),
                ('pur', models.CharField(default='0', max_length=50)),
                ('ammount', models.CharField(default='0', max_length=50)),
                ('approve', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=100)),
                ('amount', models.CharField(default='0', max_length=100)),
                ('coin', models.CharField(blank=True, default='0', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('In Progress', 'In Progress'), ('Failed', 'Failed')], default='In Progress', max_length=20)),
                ('status2', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Failed', 'Failed')], default='Debit', max_length=20)),
                ('credit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Che',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('approve', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
